export enum ErrorDomain {
  AUTH = "auth",
  VALIDATION = "validation",
  SETTLEMENT = "settlement",
  PAYMENT = "payment",
  RECONCILIATION = "reconciliation",
  BLOCKCHAIN = "blockchain",
  PORTFOLIO = "portfolio",
  RATE_LIMIT = "rate_limit",
  SYSTEM = "system",
}

export enum ErrorCode {
  // Generic & System
  INTERNAL_ERROR = "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  DATABASE_ERROR = "DATABASE_ERROR",
  DEPENDENCY_TIMEOUT = "DEPENDENCY_TIMEOUT",
  NOT_FOUND = "NOT_FOUND",
  RATE_LIMITED = "RATE_LIMITED",

  // Validation
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_PARAMETER = "INVALID_PARAMETER",
  MALFORMED_PAYLOAD = "MALFORMED_PAYLOAD",
  PRECONDITION_FAILED = "PRECONDITION_FAILED",

  // Auth & RBAC
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
  SESSION_TERMINATED = "SESSION_TERMINATED",

  // Settlement & Payment
  SETTLEMENT_FAILED = "SETTLEMENT_FAILED",
  SETTLEMENT_TIMEOUT = "SETTLEMENT_TIMEOUT",
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  DUPLICATE_PAYMENT_SUBMISSION = "DUPLICATE_PAYMENT_SUBMISSION",
  PAYMENT_METHOD_UNSUPPORTED = "PAYMENT_METHOD_UNSUPPORTED",

  // Reconciliation
  RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH",
  INVOICE_NOT_FOUND = "INVOICE_NOT_FOUND",
  TRANSACTION_UNCONFIRMED = "TRANSACTION_UNCONFIRMED",

  // Blockchain / Stellar / Oracle
  STELLAR_NETWORK_ERROR = "STELLAR_NETWORK_ERROR",
  HORIZON_TIMEOUT = "HORIZON_TIMEOUT",
  INVALID_TRANSACTION_ENVELOPE = "INVALID_TRANSACTION_ENVELOPE",
  NONCE_EXPIRED = "NONCE_EXPIRED",
  ORACLE_VERIFICATION_FAILED = "ORACLE_VERIFICATION_FAILED",

  // Portfolio & DeFi
  PORTFOLIO_NOT_FOUND = "PORTFOLIO_NOT_FOUND",
  OPTIMIZATION_FAILED = "OPTIMIZATION_FAILED",
  RISK_LIMIT_EXCEEDED = "RISK_LIMIT_EXCEEDED",
  ASSET_UNSUPPORTED = "ASSET_UNSUPPORTED",

  // Business Conflict
  CONFLICT = "CONFLICT",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  DUPLICATE_ENTRY = "DUPLICATE_ENTRY",
}
